#!/usr/bin/env groovy

library identifier: 'shared-library-java-master@master', retriever: modernSCM(
    [$class: 'GitSCMSource',
     remote: 'https://gitlab.com/awabrajpoot88/shared-library-java-master',
     credentialsId: 'gitlab-user'
    ]
) 

def gv 

pipeline {
    tools {
        maven 'Maven-3.8.6'
    }
    agent any
    stages {
        stage('init') {
            steps {
                script {
                    echo "initializing the script!"
                    gv = load('script.groovy')
                }
            }
        }
        stage('increment version'){
            steps {
                script {
                    echo "incrementing the old version of our app"
                    sh 'mvn build-helper:parse-version versions:set -DnewVersion=\\\${parsedVersion.majorVersion}.\\\${parsedVersion.minorVersion}.\\\${parsedVersion.nextIncrementalVersion} versions:commit'
                    def matcher = readFile('pom.xml') =~ '<version>(.+)</version>'
                    def version = matcher[0][1]
                    env.IMAGE_NAME = "$version-$BUILD_NUMBER"
                }
            }
        }
        stage('Build Jar') {
            steps {
                script {
                    echo "building the jar file"
                    sh 'mvn clean package'
                }
            }
        }
        stage('Build image'){
            steps {
                script {
                    echo "building the docker image of our APP!"
                    sh "docker build -t awabhassan/my-repo:${env.IMAGE_NAME} ."
                }
            }
        }
        stage('Docker login'){
            steps {
                script {
                    echo "logging in Docker!!!"
                    withCredentials([usernamePassword(credentialsId: 'docker-user' , usernameVariable: 'USER' , passwordVariable:'PASS')]){
                        "echo ${PASS} | docker login -u ${USER} --password-stdin"
                    }
                }
            }
        }
        stage('Docker Push'){
            steps {
                script {
                    echo "Pushing the Image to docker repository.."
                    sh "docker push awabhassan/my-repo:${env.IMAGE_NAME}"
                }
            }
        }
    
        stage('git commit'){
            steps {
                script {
                    echo "Pushing all the changes to git repository...."
                    withCredentials([usernamePassword(credentialsId:'gitlab-user' , usernameVariable: 'USER', passwordVariable: 'PASS')]){
                        sh 'git config --global user.name "jenkins"'
                        sh 'git config --global user.email "jenkins@example.com"'
                        sh "git remote set-url origin https://${USER}:${PASS}@gitlab.com/awabrajpoot88/java-maven-app-master.git/"
                        sh 'git add .'
                        sh 'git commit -m "-f"'
                        sh 'git push origin HEAD:feature/complete-pipeline'
                    }
                }
            }
        }
        
        stage('Deploy to EC2 Instance'){
            steps{
                script{
                    echo "deploying to EC2 instance"
                    def dockerCMD = 'docker-compose -f docker-compose.yaml up --detach'
                    sshagent(['ssh-user']){
                        sh "scp docker-compose.yaml ec2-user@54.166.179.166:/home/ec2-user"
                        sh "ssh -o StrictHostKeyChecking=no ec2-user@54.166.179.166 ${dockerCMD}"
                    }
                }
            }

        }  
    }
}